---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    

- name: Install prerequisites for Docker repository
  apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: yes

- name: Set timezone
  become: true
  timezone:
    name: "{{ time_zone }}"
  notify: Restart server